// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#ifndef _carsim_ContactPoint_h
#define _carsim_ContactPoint_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _carsim_ContactPoint carsim_ContactPoint;
struct _carsim_ContactPoint
{
    int8_t     id;
    double     z;
    double     friction;
};

/**
 * Create a deep copy of a carsim_ContactPoint.
 * When no longer needed, destroy it with carsim_ContactPoint_destroy()
 */
carsim_ContactPoint* carsim_ContactPoint_copy(const carsim_ContactPoint* to_copy);

/**
 * Destroy an instance of carsim_ContactPoint created by carsim_ContactPoint_copy()
 */
void carsim_ContactPoint_destroy(carsim_ContactPoint* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _carsim_ContactPoint_subscription_t carsim_ContactPoint_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * carsim_ContactPoint is received.
 */
typedef void(*carsim_ContactPoint_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const carsim_ContactPoint *msg, void *userdata);

/**
 * Publish a message of type carsim_ContactPoint using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int carsim_ContactPoint_publish(lcm_t *lcm, const char *channel, const carsim_ContactPoint *msg);

/**
 * Subscribe to messages of type carsim_ContactPoint using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
carsim_ContactPoint_subscription_t* carsim_ContactPoint_subscribe(
    lcm_t *lcm, const char *channel, carsim_ContactPoint_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by carsim_ContactPoint_subscribe()
 */
int carsim_ContactPoint_unsubscribe(lcm_t *lcm, carsim_ContactPoint_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int carsim_ContactPoint_subscription_set_queue_capacity(
    carsim_ContactPoint_subscription_t* subs, int num_messages);

/**
 * Encode a message of type carsim_ContactPoint into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to carsim_ContactPoint_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int carsim_ContactPoint_encode(void *buf, int offset, int maxlen, const carsim_ContactPoint *p);

/**
 * Decode a message of type carsim_ContactPoint from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with carsim_ContactPoint_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int carsim_ContactPoint_decode(const void *buf, int offset, int maxlen, carsim_ContactPoint *msg);

/**
 * Release resources allocated by carsim_ContactPoint_decode()
 * @return 0
 */
int carsim_ContactPoint_decode_cleanup(carsim_ContactPoint *p);

/**
 * Check how many bytes are required to encode a message of type carsim_ContactPoint
 */
int carsim_ContactPoint_encoded_size(const carsim_ContactPoint *p);

// LCM support functions. Users should not call these
int64_t __carsim_ContactPoint_get_hash(void);
uint64_t __carsim_ContactPoint_hash_recursive(const __lcm_hash_ptr *p);
int __carsim_ContactPoint_encode_array(
    void *buf, int offset, int maxlen, const carsim_ContactPoint *p, int elements);
int __carsim_ContactPoint_decode_array(
    const void *buf, int offset, int maxlen, carsim_ContactPoint *p, int elements);
int __carsim_ContactPoint_decode_array_cleanup(carsim_ContactPoint *p, int elements);
int __carsim_ContactPoint_encoded_array_size(const carsim_ContactPoint *p, int elements);
int __carsim_ContactPoint_clone_array(const carsim_ContactPoint *p, carsim_ContactPoint *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
