// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "carsim_State.h"

static int __carsim_State_hash_computed;
static uint64_t __carsim_State_hash;

uint64_t __carsim_State_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __carsim_State_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __carsim_State_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x73ec406c616bf9abLL
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __carsim_State_get_hash(void)
{
    if (!__carsim_State_hash_computed) {
        __carsim_State_hash = (int64_t)__carsim_State_hash_recursive(NULL);
        __carsim_State_hash_computed = 1;
    }

    return __carsim_State_hash;
}

int __carsim_State_encode_array(void *buf, int offset, int maxlen, const carsim_State *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].yaw), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].roll), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].pitch), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].vx), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].vy), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].vz), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int carsim_State_encode(void *buf, int offset, int maxlen, const carsim_State *p)
{
    int pos = 0, thislen;
    int64_t hash = __carsim_State_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __carsim_State_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __carsim_State_encoded_array_size(const carsim_State *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __double_encoded_array_size(&(p[element].x), 1);

        size += __double_encoded_array_size(&(p[element].y), 1);

        size += __double_encoded_array_size(&(p[element].z), 1);

        size += __double_encoded_array_size(&(p[element].yaw), 1);

        size += __double_encoded_array_size(&(p[element].roll), 1);

        size += __double_encoded_array_size(&(p[element].pitch), 1);

        size += __double_encoded_array_size(&(p[element].vx), 1);

        size += __double_encoded_array_size(&(p[element].vy), 1);

        size += __double_encoded_array_size(&(p[element].vz), 1);

    }
    return size;
}

int carsim_State_encoded_size(const carsim_State *p)
{
    return 8 + __carsim_State_encoded_array_size(p, 1);
}

int __carsim_State_decode_array(const void *buf, int offset, int maxlen, carsim_State *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].yaw), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].roll), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].pitch), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].vx), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].vy), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].vz), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __carsim_State_decode_array_cleanup(carsim_State *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_decode_array_cleanup(&(p[element].x), 1);

        __double_decode_array_cleanup(&(p[element].y), 1);

        __double_decode_array_cleanup(&(p[element].z), 1);

        __double_decode_array_cleanup(&(p[element].yaw), 1);

        __double_decode_array_cleanup(&(p[element].roll), 1);

        __double_decode_array_cleanup(&(p[element].pitch), 1);

        __double_decode_array_cleanup(&(p[element].vx), 1);

        __double_decode_array_cleanup(&(p[element].vy), 1);

        __double_decode_array_cleanup(&(p[element].vz), 1);

    }
    return 0;
}

int carsim_State_decode(const void *buf, int offset, int maxlen, carsim_State *p)
{
    int pos = 0, thislen;
    int64_t hash = __carsim_State_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __carsim_State_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int carsim_State_decode_cleanup(carsim_State *p)
{
    return __carsim_State_decode_array_cleanup(p, 1);
}

int __carsim_State_clone_array(const carsim_State *p, carsim_State *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_clone_array(&(p[element].x), &(q[element].x), 1);

        __double_clone_array(&(p[element].y), &(q[element].y), 1);

        __double_clone_array(&(p[element].z), &(q[element].z), 1);

        __double_clone_array(&(p[element].yaw), &(q[element].yaw), 1);

        __double_clone_array(&(p[element].roll), &(q[element].roll), 1);

        __double_clone_array(&(p[element].pitch), &(q[element].pitch), 1);

        __double_clone_array(&(p[element].vx), &(q[element].vx), 1);

        __double_clone_array(&(p[element].vy), &(q[element].vy), 1);

        __double_clone_array(&(p[element].vz), &(q[element].vz), 1);

    }
    return 0;
}

carsim_State *carsim_State_copy(const carsim_State *p)
{
    carsim_State *q = (carsim_State*) malloc(sizeof(carsim_State));
    __carsim_State_clone_array(p, q, 1);
    return q;
}

void carsim_State_destroy(carsim_State *p)
{
    __carsim_State_decode_array_cleanup(p, 1);
    free(p);
}

int carsim_State_publish(lcm_t *lc, const char *channel, const carsim_State *p)
{
      int max_data_size = carsim_State_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = carsim_State_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _carsim_State_subscription_t {
    carsim_State_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void carsim_State_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    carsim_State p;
    memset(&p, 0, sizeof(carsim_State));
    status = carsim_State_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding carsim_State!!!\n", status);
        return;
    }

    carsim_State_subscription_t *h = (carsim_State_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    carsim_State_decode_cleanup (&p);
}

carsim_State_subscription_t* carsim_State_subscribe (lcm_t *lcm,
                    const char *channel,
                    carsim_State_handler_t f, void *userdata)
{
    carsim_State_subscription_t *n = (carsim_State_subscription_t*)
                       malloc(sizeof(carsim_State_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 carsim_State_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg carsim_State LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int carsim_State_subscription_set_queue_capacity (carsim_State_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int carsim_State_unsubscribe(lcm_t *lcm, carsim_State_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe carsim_State_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

